title: "plauche.github.io"
author: "Ryan Plauche"
description: "Hello there"
permalink: /:title/
lang: "en"
date_format: "%B %d, %Y"

# Layout

sidebar: true                # show a sidebar instead of the usual header
show_excerpts: false         # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_title: false            # always keep the site title visible

# Styling

dark_header: false           # always keep the header dark
minimal: false               # use simpler style

# Menu

navigation:
  - {file: "index.html", icon: home}
  - {file: "about.md", icon: address-card}

external:                    # see http://fontawesome.com/icons
  - {title: Github, icon: github, url: "https://github.com/plauche"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/ryan-plauche-235b021/"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/plauplauplau"}

comments:
#  disqus: ""                # see https://disqus.com/
#  isso: ""                  # see https://posativ.org/isso/

plugins:
 - jekyll-feed
